title = "Bad Blood"

category = "forensics"
difficulty = 3
author = "elbee"
discord = "elbee3779"
flag = "pctf{3v3nt_l0gs_reve4l_al1_a981eb}"

description = '''
Nothing is more dangerous than a bad guy that used to be a good guy. Something's going on... please talk with our incident response team.

Author: elbee3779
'''

# Writeup
Answer the questions on the remote using the event log viewer with the evtx given of the compromised machine
