title="RTL Warm up"

category="misc"
difficulty=2
author='''<a href="https://databuoy.com/">Databuoy</a>"
flag="PCTF{RTL_i$_D@D_0F_H@rdw@r3}"

description='''
Let's Warm up.
Spartan's wanted to create their own ASIC, to secure doors.
One of the spy was able to extract the simulation file,
can you find the password to the door?

Note: The spaces are _
'''

