title = "sanitizer"

category = "pwn"
difficulty = 7
flag = "pctf{s4n1tiz3_my_m1ps_f981ab}"

description = '''
We made a project for our Intro to Networking class! I hope you use it to make the internet a more secure place :)

Author: Shiloh Smiles (arcticx) and Dylan (elbee3779)
'''

Stack leak + mips shellcode
