title = "AI? PRNG"
category = "rev"
difficulty = 8
author = "Brandon \"Veryyes\" Wong"
discord = "Veryyes"
flag = "pctf{d33p_le@rnING}"
tester = ""
description = '''
I heard those tech cool buzz words use matrices. Well my (very legit) PRNG also uses matricies, can I slap AI/ML/Deep Learning on it too???? Unless???
'''